enum
{
	HAR_a = 4,
	HAR_b,HAR_c,HAR_d,HAR_e,HAR_f,HAR_g,HAR_h,HAR_i,HAR_j,HAR_k,HAR_l,HAR_m,HAR_n,HAR_o,HAR_p,
	HAR_q,HAR_r,HAR_s,HAR_t,HAR_u,HAR_v,HAR_w,HAR_x,HAR_y,HAR_z,

	HAR_1=30,HAR_2,HAR_3,HAR_4,HAR_5,HAR_6,HAR_7,HAR_8,HAR_9,HAR_0,

	HAR_ENTER   = 40,
	HAR_ESCAPE  = 41,
	HAR_SPACE   = 44,
	HAR_MINUS   = 45,
	HAR_PLUS    = 46,

	HAR_RIGHT=79,HAR_LEFT,HAR_DOWN,HAR_UP,
	HAR_LAST
};
